### ISSUE TITLE
Add Retry Logic

### ISSUE THREAD

**Issue by inkrement** [postaddictme/instagram-php-scraper#104]
Especially Unirest seems to produce errors from time to time. I already received the following exceptions on running correct code. Therefore, some kind of retry logic would be appropriate.

```
PHP Fatal error:  Uncaught Unirest\Exception: transfer closed with 4396 bytes remaining to read in /home/chris/instagram/vendor/mashape/unirest-php/src/Unirest/Request.php:476
Stack trace:
#0 /home/chris/instagram/vendor/mashape/unirest-php/src/Unirest/Request.php(236): Unirest\Request::send('GET', 'https://www.ins...', NULL, Array, NULL, NULL)
#1 /home/chris/instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(557): Unirest\Request::get('https://www.ins...', Array)
#2 /home/chris/instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(520): InstagramScraper\Instagram->isLoggedIn(Array)
#3 /home/chris/instagram/loadUser.php(16): InstagramScraper\Instagram->login()
#4 {main}
  thrown in /home/chris/instagram/vendor/mashape/unirest-php/src/Unirest/Request.php on line 476
```

or

```
PHP Fatal error:  Uncaught Unirest\Exception: Unknown SSL protocol error in connection to www.instagram.com:443  in /home/chris/instagram/vendor/mashape/unirest-php/src/Unirest/Request.php:476
Stack trace:
#0 /home/chris/instagram/vendor/mashape/unirest-php/src/Unirest/Request.php(292): Unirest\Request::send('POST', 'https://www.ins...', Array, Array, NULL, NULL)
#1 /home/chris/instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(313): Unirest\Request::post('https://www.ins...', Array, Array)
#2 /home/chris/instagram/loadUser.php(21): InstagramScraper\Instagram->getAccountById('250928744')
#3 {main}
```

or

```
PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong. Please report issue. in /home/chris/instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:535
Stack trace:
#0 /home/chris/instagram/loadUser.php(16): InstagramScraper\Instagram->login()
#1 {main}
  thrown in /home/chris/instagram/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 535
```

**Comment by raiym** [comment]
No plans for now
