### ISSUE TITLE
Connection refused for URI https://www.instagram.com

### ISSUE THREAD

**Issue by amiria703** [postaddictme/instagram-php-scraper#1042]
```
<b>Fatal error</b>:  Uncaught GuzzleHttp\Exception\ConnectException: Connection refused for URI https://www.instagram.com in \vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php:324
Stack trace:
#0 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(241): GuzzleHttp\Handler\StreamHandler-&gt;GuzzleHttp\Handler\{closure}()
#1 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(335): GuzzleHttp\Handler\StreamHandler-&gt;createResource(Object(Closure))
#2 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php(58): GuzzleHttp\Handler\StreamHandler-&gt;createStream(Object(GuzzleHttp\Psr7\Request), Array)
#3 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\StreamHandler-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#5 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(55): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\Middleware.php(61): GuzzleHttp\RedirectMiddleware-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\Client.php(331): GuzzleHttp\HandlerStack-&gt;__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\Client.php(107): GuzzleHttp\Client-&gt;transfer(Object(GuzzleHttp\Psr7\Request), Array)
#10 C:\Users\1\Desktop\api\core\app\vendor\guzzlehttp\guzzle\src\Client.php(137): GuzzleHttp\Client-&gt;sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#11 C:\Users\1\Desktop\api\core\app\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Http\Request.php(49): GuzzleHttp\Client-&gt;sendRequest(Object(GuzzleHttp\Psr7\Request))
#12 C:\Users\1\Desktop\api\core\app\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Http\Request.php(67): InstagramScraper\Http\Request::send('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#13 C:\Users\1\Desktop\api\core\app\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php(2079): InstagramScraper\Http\Request::get('https://www.ins...', Array)
#14 C:\Users\1\Desktop\api\core\app\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php(2039): InstagramScraper\Instagram-&gt;isLoggedIn(Array)

```

What to do?

**Comment by amiria703** [comment]
Using apache instead of ```php -S``` command solved problem
