### ISSUE TITLE
errors  page 500 

### ISSUE THREAD

**Issue by istorepro** [postaddictme/instagram-php-scraper#262]
[24-Jan-2018 19:48:10 Europe/London] PHP Fatal error:  Uncaught exception 'InstagramScraper\Exception\InstagramException' with message 'Account with this username does not exist' in /home/imoham3d/public_html/imohamed/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:556
Stack trace:
#0 /home/imoham3d/public_html/imohamed/insta.php(68): InstagramScraper\Instagram->getAccount('imohamed')
#1 /home/imoham3d/public_html/imohamed/insta.php(79): Following('imohamed')
#2 {main}
  thrown in /home/imoham3d/public_html/imohamed/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 556

**Comment by rhcarlosweb** [comment]
I think there was some update in instagram, here I was same problem because "/? __ a = 1" it's not working, but it seems  to be working again 👍
