### ISSUE TITLE
getAccountById() does not work (without authentication?)

### ISSUE THREAD

**Issue by mfkrause** [postaddictme/instagram-php-scraper#447]
If I try to use getAccountById($id), it will give me an `InstagramException`:
`Fatal error: Uncaught exception 'InstagramScraper\Exception\InstagramException' with message 'Response does not JSON' in /home/***/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:814 Stack trace: #0 /home/***/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(791): InstagramScraper\Instagram->getUsernameById(***) #1 /home/***/dashboard/inc/scripts.php(51): InstagramScraper\Instagram->getAccountById(***) #2 /home/***/dashboard/test.php(3): updateIgStats('instagram') #3 {main} thrown in /home/***/vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 814`

This is just what I used to make sure the problem is within the getAccountById() function:
```
$account = $instagram->getAccount("instagram");
$id = $account->getId();
$account = $instagram->getAccountById($id);
echo $account->getUsername();
```

While the getAccount("instagram") works fine (and even gets the ID of the account), the getAccountById($id) does not.

**Comment by mfkrause** [comment]
Sorry, just noticed this is a [duplicate](url
https://github.com/postaddictme/instagram-php-scraper/issues/433).
