### ISSUE TITLE
Errors, errors, errors... PHP Fatal error:  Uncaught Error: Class 'Instagram'

### ISSUE THREAD

**Issue by nfxpnk** [postaddictme/instagram-php-scraper#562]
**Windows 10**
**PHP 7.2.4**

Code from readme.md is

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$instagram = Instagram::withCredentials('uuuuu', '******');
$instagram->login();
$account = $instagram->getAccountById(3);
echo $account->getUsername();
```

`php test.php`

Result is:

```
$ php test.php
PHP Fatal error:  Uncaught Error: Class 'Instagram' not found in C:\Users\user\php\test\test.php:4
Stack trace:
#0 {main}
  thrown in C:\Users\user\php\test\test.php on line 4

Fatal error: Uncaught Error: Class 'Instagram' not found in C:\Users\user\php\test\test.php:4
Stack trace:
#0 {main}
  thrown in C:\Users\user\php\test\test.php on line 4
```
Ok, maybe it's just a typo in readme.md right?

Let's try code example from examples folder

```php
<?php
require __DIR__ . '/vendor/autoload.php';

$instagram = \InstagramScraper\Instagram::withCredentials('uuuu', '*****', '/path/to/cache/folder');
$instagram->login();
$account = $instagram->getAccountById(3);
echo $account->getUsername();
```

Result is:

```
$ php test.php
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to InstagramScraper\Instagram::withCredentials() must be an instance of Psr\SimpleCache\CacheInterface, string given, called in C:\Users\user\php\test\test.php on line 4 and defined in C:\Users\user\php\test\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php:54
Stack trace:
#0 C:\Users\user\php\test\test.php(4): InstagramScraper\Instagram::withCredentials('uuuu', '*****', '/path/to/cache/...')
#1 {main}
  thrown in C:\Users\user\php\test\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 54

Fatal error: Uncaught TypeError: Argument 3 passed to InstagramScraper\Instagram::withCredentials() must be an instance of Psr\SimpleCache\CacheInterface, string given, called in C:\Users\user\php\test\test.php on line 4 and defined in C:\Users\user\php\test\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php:54
Stack trace:
#0 C:\Users\user\php\test\test.php(4): InstagramScraper\Instagram::withCredentials('uuuu', '*****', '/path/to/cache/...')
#1 {main}
  thrown in C:\Users\user\php\test\vendor\raiym\instagram-php-scraper\src\InstagramScraper\Instagram.php on line 54
```
What??

Ok, maybe it's a typo too, let's try to make it work anyway?

Code:
```php
<?php
require __DIR__ . '/vendor/autoload.php';
use Phpfastcache\Helper\Psr16Adapter;

$instagram = \InstagramScraper\Instagram::withCredentials('uuuu', '******', new Psr16Adapter('cache'));
$instagram->login();
$account = $instagram->getAccountById(3);
echo $account->getUsername();
```
Result is:

```
Fatal error: Uncaught Phpfastcache\Exceptions\PhpfastcacheDriverException: Class "Phpfastcache\Drivers\Cache\Driver" does not implement "Phpfastcache\Core\Pool\ExtendedCacheItemPoolInterface" in C:\Users\user\php\test\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\CacheManager.php:606
Stack trace:
#0 C:\Users\user\php\test\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\CacheManager.php(126): Phpfastcache\CacheManager::validateDriverClass('Phpfastcache\\Dr...')
#1 C:\Users\user\php\test\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\Helper\Psr16Adapter.php(52): Phpfastcache\CacheManager::getInstance('Cache', Object(Phpfastcache\Config\ConfigurationOption))
#2 C:\Users\user\php\test\test.php(5): Phpfastcache\Helper\Psr16Adapter->__construct('cache')
#3 {main}
  thrown in C:\Users\user\php\test\vendor\phpfastcache\phpfastcache\lib\Phpfastcache\CacheManager.php on line 606
```

I don't know, any suggestions?

Thanks

**Comment by this-is-rafa** [comment]
Did you figure it out? I can't tell you why because I barely get it myself, but if you change `new Psr16Adapter('cache')` to `new Psr16Adapter('Files')` it should work.

**Comment by spapapan** [comment]
I have the same issue
