### ISSUE TITLE
Can't login with email code

### ISSUE THREAD

**Issue by nleo** [postaddictme/instagram-php-scraper#798]
```php
<?php
use Phpfastcache\Helper\Psr16Adapter;

require __DIR__ . '/vendor/autoload.php';

$instagram = \InstagramScraper\Instagram::withCredentials(new \GuzzleHttp\Client(), 'xxx', 'xxx', new Psr16Adapter('Files'));
$instagram->login(false, true);
$instagram->saveSession();
sleep(2); // Delay to mimic user

$username = 'kevin';
$followers = [];
$account = $instagram->getAccount($username);
sleep(1);
$followers = $instagram->getFollowing($account->getId(), 1000, 100, true); // Get 1000 followings of 'kevin', 100 a time with random delay between requests
echo '<pre>' . json_encode($followers, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . '</pre>';
```

```
$ php7.2 getAccountFollowings.php
Message with security code sent to: Email: xxx
Enter security code: 111111
PHP Fatal error:  Uncaught InstagramScraper\Exception\InstagramAuthException: Something went wrong when try two step verification and enter security code. Please report issue. in vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php:1789
Stack trace:
#0 vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php(1650): InstagramScraper\Instagram->verifyTwoStep(Object(InstagramScraper\Http\Response), Array, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
#1 getAccountFollowings.php(7): InstagramScraper\Instagram->login(false, Object(InstagramScraper\TwoStepVerification\ConsoleVerification))
#2 {main}
  thrown in vendor/raiym/instagram-php-scraper/src/InstagramScraper/Instagram.php on line 1789
```

**Comment by tschni** [comment]
Possibly the same problem as with me? #797

**Comment by nleo** [comment]
I use another package with integration with firefox https://instaloader.github.io/troubleshooting.html#login-error
