### ISSUE TITLE
Uncaught InstagramScraper\Exception\InstagramNotFoundException: User with this id not found in

### ISSUE THREAD

**Issue by filippodicostanzo** [postaddictme/instagram-php-scraper#85]
When i try to get the username by getAccountById('193886659') the script return 
this error Uncaught InstagramScraper\Exception\InstagramNotFoundException: User with this id not found

I tried with my id account and the return is same.

**Comment by raiym** [comment]
@filippodicostanzo could you provide steps to reproduce this issue? 
Because on test cases everthing works as expected

**Comment by saeidg95** [comment]
I have this problem too
`[23-Mar-2017 20:34:53 UTC] PHP Fatal error:  Using $this when not in object context in /home/artnema/public_html/instagram/scraper/InstagramScraper/Instagram.php on line 268
[23-Mar-2017 20:42:59 UTC] PHP Fatal error:  Uncaught exception 'InstagramScraper\Exception\InstagramNotFoundException' with message 'User with this id not found' in /home/artnema/public_html/instagram/scraper/InstagramScraper/Instagram.php:299
Stack trace:
#0 /home/artnema/public_html/instagram/instabot.php(197): InstagramScraper\Instagram->getAccountById('25025320')
#1 /home/artnema/public_html/instagram/instabot.php(224): callback(Array)
#2 {main}
  thrown in /home/artnema/public_html/instagram/scraper/InstagramScraper/Instagram.php on line 299`

and this

`[23-Mar-2017 20:34:53 UTC] PHP Strict Standards:  Non-static method InstagramScraper\Instagram::getAccountById() should not be called statically in /home/artnema/public_html/instagram/instabot.php on line 197
[23-Mar-2017 20:34:53 UTC] PHP Strict Standards:  Non-static method InstagramScraper\Instagram::getContentsFromUrl() should not be called statically in /home/artnema/public_html/instagram/scraper/InstagramScraper/Instagram.php on line 294`

**Comment by raiym** [comment]
Update to the last library version
