### ISSUE TITLE
$expiration must be an object implementing the DateTimeInterface

### ISSUE THREAD

**Issue by sfatfarma** [postaddictme/instagram-php-scraper#86]
Hello, I tested this script and it works well. But since you implemented the session caching, when I execute it second time in a row, I recieve this exception:

Exception 'InvalidArgumentException' with message '$expiration must be an object implementing the DateTimeInterface' in /home/coderevo/public_html/testing/wp-content/plugins/instamatic-instagram-post-generator/res/Instagram-get/phpCache/src/phpFastCache/Cache/ItemBaseTrait.php:134 Stack trace: #0 /home/coderevo/public_html/testing/wp-content/plugins/instamatic-instagram-post-generator/res/Instagram-get/phpCache/src/phpFastCache/Core/StandardPsr6StructureTrait.php(64): phpFastCache\Drivers\Files\Item->expiresAt(Object(DateTime)) #1 /home/coderevo/public_html/testing/wp-content/plugins/instamatic-instagram-post-generator/res/Instagram-get/InstagramScraper/Instagram.php(512): phpFastCache\Core\DriverAbstract->getItem('sfatfarma') #2 /home/coderevo/public_html/testing/wp-content/plugins/instamatic-instagram-post-generator/instamatic-instagram-post-generator.php(685): InstagramScraper\Instagram->login(true) #3 /home/coderevo/public_html/testing/wp-content/plugins/instamatic-instagram-post-generator/instamatic-instagram-post-generator.php(385): instamatic_run_rule('1', 0) #4 [internal function]: instamatic_run_my_action_callback('') #5 /home/coderevo/public_html/testing/wp-includes/class-wp-hook.php(298): call_user_func_array('instamatic_run_...', Array) #6 /home/coderevo/public_html/testing/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #7 /home/coderevo/public_html/testing/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #8 /home/coderevo/public_html/testing/wp-admin/admin-ajax.php(91): do_action('wp_ajax_instama...') #9 {main}!

Thanks!

**Comment by sfatfarma** [comment]
Also, I can reproduce this only on Linux based servers (on my Windows based localhost it works well).

**Comment by sfatfarma** [comment]
Also, this only happens when I call the login method with force reauth argument ->login(true);

**Comment by sfatfarma** [comment]
Sorry, I investigated further an the script requires now PHP 5.5 because of  DateTimeInterface. Issue closed, sorry.
